version: "3.9"

services:
  api:
    build:
      context: $API_PATH
      dockerfile: Dockerfile
    image: human-resources-api
    container_name: human-resources-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - db

  client:
    build:
      context: $CLIENT_PATH
      dockerfile: Dockerfile
      args:
        - API_URL=$API_URL
        - CLIENT_PORT_EXPOSE=$CLIENT_PORT_EXPOSE
    image: human-resources-client
    container_name: human-resources-client
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - $CLIENT_PORT:$CLIENT_PORT_EXPOSE

  db:
    image: mysql:8.0.31-debian
    container_name: human-resources-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$API_DATABASE_USER_PASSWORD
      - MYSQL_DATABASE=$API_DATABASE_NAME
    ports:
      - $API_DATABASE_PORT:$API_DATABASE_PORT
    volumes:
      - human-resources-db:/var/lib/mysql

volumes:
  human-resources-db:
    driver: local
