version: "3.9"

services:
  api:
    build:
      context: $API_PATH
      dockerfile: Dockerfile
    image: human-resources-api
    container_name: human-resources-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - API_PORT=$API_PORT
      - DATABASE_HOST=$API_DATABASE_HOST
      - DATABASE_PORT=$API_DATABASE_PORT
      - DATABASE_USER_NAME=$API_DATABASE_USER_NAME
      - DATABASE_USER_PASSWORD=$API_DATABASE_USER_PASSWORD
      - DATABASE_NAME=$API_DATABASE_NAME
      - NODE_ENV=production
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - api-db

  api-db:
    build:
      context: $API_DB_PATH
      dockerfile: Dockerfile
    image: human-resources-api-db
    container_name: human-resources-api-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$API_DATABASE_USER_PASSWORD
      - MYSQL_DATABASE=$API_DATABASE_NAME
    ports:
      - $API_DATABASE_PORT:$API_DATABASE_PORT
    volumes:
      - human-resources-api-db:/var/lib/mysql

  client:
    build:
      context: $CLIENT_PATH
      dockerfile: Dockerfile
      args:
        - API_URL=$API_URL
        - CLIENT_PORT_EXPOSE=$CLIENT_PORT_EXPOSE
    image: human-resources-client
    container_name: human-resources-client
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - API_URL=$API_URL
      - NODE_ENV=production
    ports:
      - $CLIENT_PORT:$CLIENT_PORT_EXPOSE

volumes:
  human-resources-api-db:
    driver: local
