version: "3.9"

services:
  api:
    build:
      context: $API_PATH
      dockerfile: Dockerfile
    image: human-resources-api
    container_name: human-resources-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - $API_PORT:$API_PORT
    depends_on:
      - api-db

  api-db:
    image: mysql:8.0.31-debian
    container_name: human-resources-api-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=$API_DATABASE_USER_NAME
      - MYSQL_PASSWORD=$API_DATABASE_USER_PASSWORD
      - MYSQL_DATABASE=$API_DATABASE_NAME
    ports:
      - $API_DATABASE_PORT:$MYSQL_EXPOSED_PORT
    volumes:
      - human-resources-api-db:/var/lib/mysql

  client:
    build:
      context: $CLIENT_PATH
      dockerfile: Dockerfile
      args:
        - API_URL=$API_URL
        - CLIENT_AUTHORITY=$CLIENT_AUTHORITY
        - CLIENT_ID=$CLIENT_ID
        - CLIENT_PORT_EXPOSE=$CLIENT_PORT_EXPOSE
    image: human-resources-client
    container_name: human-resources-client
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - $CLIENT_PORT:$CLIENT_PORT_EXPOSE

  identity:
    image: bitnami/keycloak:20-debian-11
    container_name: human-resources-identity
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=$IDENTITY_ADMIN_NAME
      - KEYCLOAK_ADMIN_PASSWORD=$IDENTITY_ADMIN_PASSWORD
      - KEYCLOAK_MANAGEMENT_USER=$IDENTITY_MANAGEMENT_USER_NAME
      - KEYCLOAK_MANAGEMENT_PASSWORD=$IDENTITY_MANAGEMENT_USER_PASSWORD

      - KEYCLOAK_DATABASE_HOST=$IDENTITY_DATABASE_HOST
      - KEYCLOAK_DATABASE_PORT=$IDENTITY_DATABASE_PORT
      - KEYCLOAK_DATABASE_NAME=$IDENTITY_DATABASE_NAME
      - KEYCLOAK_DATABASE_USER=$IDENTITY_DATABASE_USER_NAME
      - KEYCLOAK_DATABASE_PASSWORD=$IDENTITY_DATABASE_USER_PASSWORD

      - KEYCLOAK_ENABLE_STATISTICS=true
    ports:
      - $IDENTITY_PORT:$IDENTITY_PORT_EXPOSE
    depends_on:
      - identity-db

  identity-db:
    image: bitnami/postgresql:15-debian-11
    container_name: human-resources-identity-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRESQL_USERNAME=$IDENTITY_DATABASE_USER_NAME
      - POSTGRESQL_PASSWORD=$IDENTITY_DATABASE_USER_PASSWORD
      - POSTGRESQL_DATABASE=$IDENTITY_DATABASE_NAME
    ports:
      - $IDENTITY_DATABASE_PORT:$IDENTITY_DATABASE_PORT
    volumes:
      - human-resources-identity-db:/bitnami/postgresql

volumes:
  human-resources-api-db:
    driver: local
  human-resources-identity-db:
    driver: local
